version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      
  pre_build:
    commands:
      - docker build -t todolist:app .
  build:
    commands:
      - docker images
      - docker run helloworld echo "Hello, World!" 
