version: 0.2 

phases: 
  install:
    runtime-versions:
        docker: 18
    commands:

  pre_build:
    commands:
    - echo Logging in to Amazon ECR....
    
    
  
  build: 
    commands: 
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t todolist:app .

    - docker tag todolist:app $registry.hub.docker.com/usama911:$todolist
  post_build: 
    commands: 
    - echo Build completed on `date` 
    - echo pushing to repo
    - docker push $registry.hub.docker.com/usama911:$todolist
    
  
