"""empty message

Revision ID: 2e9715729d18
Revises: 3f49ec5d1299
Create Date: 2015-01-17 21:47:40.934000

"""

# revision identifiers, used by Alembic.
revision = '2e9715729d18'
down_revision = '3f49ec5d1299'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'todo', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column(u'todo', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.add_column(u'todo', sa.Column('todolist_id', sa.Integer(), nullable=True))
    op.drop_column(u'todo', 'timestamp')
    op.drop_column(u'todo', 'is_completed')
    op.create_index(op.f('ix_todo_created_at'), 'todo', ['created_at'], unique=False)
    op.create_index(op.f('ix_todo_finished_at'), 'todo', ['finished_at'], unique=False)
    op.drop_index('ix_todo_timestamp', table_name='todo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_todo_timestamp', 'todo', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_todo_finished_at'), table_name='todo')
    op.drop_index(op.f('ix_todo_created_at'), table_name='todo')
    op.add_column(u'todo', sa.Column('is_completed', sa.BOOLEAN(), nullable=False))
    op.add_column(u'todo', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_column(u'todo', 'todolist_id')
    op.drop_column(u'todo', 'finished_at')
    op.drop_column(u'todo', 'created_at')
    op.drop_table('todolist')
    ### end Alembic commands ###
