"""empty message

Revision ID: eff90419b076
Revises: None
Create Date: 2016-09-24 20:15:22.786236

"""

# revision identifiers, used by Alembic.
revision = "eff90419b076"
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=64), nullable=True),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("member_since", sa.DateTime(), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "todolist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("creator", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["creator"], ["user.username"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "todo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("is_finished", sa.Boolean(), nullable=True),
        sa.Column("creator", sa.String(length=64), nullable=True),
        sa.Column("todolist_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["creator"], ["user.username"]),
        sa.ForeignKeyConstraint(["todolist_id"], ["todolist.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_todo_created_at"), "todo", ["created_at"], unique=False)
    op.create_index(op.f("ix_todo_finished_at"), "todo", ["finished_at"], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_todo_finished_at"), table_name="todo")
    op.drop_index(op.f("ix_todo_created_at"), table_name="todo")
    op.drop_table("todo")
    op.drop_table("todolist")
    op.drop_table("user")
    ### end Alembic commands ###
